//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionCalculadora.ServicioCalculadora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://proyectoCalculadora/", ConfigurationName="ServicioCalculadora.Calculadora")]
    public interface Calculadora {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.sqrtResponse sqrt(AplicacionCalculadora.ServicioCalculadora.sqrtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sqrtResponse> sqrtAsync(AplicacionCalculadora.ServicioCalculadora.sqrtRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.powResponse pow(AplicacionCalculadora.ServicioCalculadora.powRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.powResponse> powAsync(AplicacionCalculadora.ServicioCalculadora.powRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.sumarResponse sumar(AplicacionCalculadora.ServicioCalculadora.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sumarResponse> sumarAsync(AplicacionCalculadora.ServicioCalculadora.sumarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.restarResponse restar(AplicacionCalculadora.ServicioCalculadora.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.restarResponse> restarAsync(AplicacionCalculadora.ServicioCalculadora.restarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.dividirResponse dividir(AplicacionCalculadora.ServicioCalculadora.dividirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.dividirResponse> dividirAsync(AplicacionCalculadora.ServicioCalculadora.dividirRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.multiplicarResponse multiplicar(AplicacionCalculadora.ServicioCalculadora.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.multiplicarResponse> multiplicarAsync(AplicacionCalculadora.ServicioCalculadora.multiplicarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse fraccionUno(AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse> fraccionUnoAsync(AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://proyectoCalculadora/).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AplicacionCalculadora.ServicioCalculadora.cuadradoResponse cuadrado(AplicacionCalculadora.ServicioCalculadora.cuadradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.cuadradoResponse> cuadradoAsync(AplicacionCalculadora.ServicioCalculadora.cuadradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrt", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class sqrtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqrtRequest() {
        }
        
        public sqrtRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrtResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class sqrtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrtResponse() {
        }
        
        public sqrtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public powRequest() {
        }
        
        public powRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sumarRequest() {
        }
        
        public sumarRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class restarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public restarRequest() {
        }
        
        public restarRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class restarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public restarResponse() {
        }
        
        public restarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividir", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class dividirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public dividirRequest() {
        }
        
        public dividirRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividirResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class dividirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dividirResponse() {
        }
        
        public dividirResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class multiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public multiplicarRequest() {
        }
        
        public multiplicarRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class multiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplicarResponse() {
        }
        
        public multiplicarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fraccionUno", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class fraccionUnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public fraccionUnoRequest() {
        }
        
        public fraccionUnoRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fraccionUnoResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class fraccionUnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public fraccionUnoResponse() {
        }
        
        public fraccionUnoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuadrado", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class cuadradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public cuadradoRequest() {
        }
        
        public cuadradoRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuadradoResponse", WrapperNamespace="http://proyectoCalculadora/", IsWrapped=true)]
    public partial class cuadradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public cuadradoResponse() {
        }
        
        public cuadradoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraChannel : AplicacionCalculadora.ServicioCalculadora.Calculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<AplicacionCalculadora.ServicioCalculadora.Calculadora>, AplicacionCalculadora.ServicioCalculadora.Calculadora {
        
        public CalculadoraClient() {
        }
        
        public CalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.sqrtResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.sqrt(AplicacionCalculadora.ServicioCalculadora.sqrtRequest request) {
            return base.Channel.sqrt(request);
        }
        
        public double sqrt(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.sqrtRequest inValue = new AplicacionCalculadora.ServicioCalculadora.sqrtRequest();
            inValue.arg0 = arg0;
            AplicacionCalculadora.ServicioCalculadora.sqrtResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).sqrt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sqrtResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.sqrtAsync(AplicacionCalculadora.ServicioCalculadora.sqrtRequest request) {
            return base.Channel.sqrtAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sqrtResponse> sqrtAsync(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.sqrtRequest inValue = new AplicacionCalculadora.ServicioCalculadora.sqrtRequest();
            inValue.arg0 = arg0;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).sqrtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.powResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.pow(AplicacionCalculadora.ServicioCalculadora.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.powRequest inValue = new AplicacionCalculadora.ServicioCalculadora.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            AplicacionCalculadora.ServicioCalculadora.powResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.powResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.powAsync(AplicacionCalculadora.ServicioCalculadora.powRequest request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.powResponse> powAsync(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.powRequest inValue = new AplicacionCalculadora.ServicioCalculadora.powRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.sumarResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.sumar(AplicacionCalculadora.ServicioCalculadora.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public double sumar(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.sumarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.sumarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            AplicacionCalculadora.ServicioCalculadora.sumarResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sumarResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.sumarAsync(AplicacionCalculadora.ServicioCalculadora.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.sumarResponse> sumarAsync(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.sumarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.sumarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.restarResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.restar(AplicacionCalculadora.ServicioCalculadora.restarRequest request) {
            return base.Channel.restar(request);
        }
        
        public double restar(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.restarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.restarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            AplicacionCalculadora.ServicioCalculadora.restarResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.restarResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.restarAsync(AplicacionCalculadora.ServicioCalculadora.restarRequest request) {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.restarResponse> restarAsync(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.restarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.restarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.dividirResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.dividir(AplicacionCalculadora.ServicioCalculadora.dividirRequest request) {
            return base.Channel.dividir(request);
        }
        
        public double dividir(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.dividirRequest inValue = new AplicacionCalculadora.ServicioCalculadora.dividirRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            AplicacionCalculadora.ServicioCalculadora.dividirResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).dividir(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.dividirResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.dividirAsync(AplicacionCalculadora.ServicioCalculadora.dividirRequest request) {
            return base.Channel.dividirAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.dividirResponse> dividirAsync(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.dividirRequest inValue = new AplicacionCalculadora.ServicioCalculadora.dividirRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).dividirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.multiplicarResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.multiplicar(AplicacionCalculadora.ServicioCalculadora.multiplicarRequest request) {
            return base.Channel.multiplicar(request);
        }
        
        public double multiplicar(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.multiplicarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.multiplicarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            AplicacionCalculadora.ServicioCalculadora.multiplicarResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.multiplicarResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.multiplicarAsync(AplicacionCalculadora.ServicioCalculadora.multiplicarRequest request) {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.multiplicarResponse> multiplicarAsync(double arg0, double arg1) {
            AplicacionCalculadora.ServicioCalculadora.multiplicarRequest inValue = new AplicacionCalculadora.ServicioCalculadora.multiplicarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).multiplicarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.fraccionUno(AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest request) {
            return base.Channel.fraccionUno(request);
        }
        
        public double fraccionUno(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest inValue = new AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest();
            inValue.arg0 = arg0;
            AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).fraccionUno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.fraccionUnoAsync(AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest request) {
            return base.Channel.fraccionUnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.fraccionUnoResponse> fraccionUnoAsync(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest inValue = new AplicacionCalculadora.ServicioCalculadora.fraccionUnoRequest();
            inValue.arg0 = arg0;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).fraccionUnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionCalculadora.ServicioCalculadora.cuadradoResponse AplicacionCalculadora.ServicioCalculadora.Calculadora.cuadrado(AplicacionCalculadora.ServicioCalculadora.cuadradoRequest request) {
            return base.Channel.cuadrado(request);
        }
        
        public double cuadrado(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.cuadradoRequest inValue = new AplicacionCalculadora.ServicioCalculadora.cuadradoRequest();
            inValue.arg0 = arg0;
            AplicacionCalculadora.ServicioCalculadora.cuadradoResponse retVal = ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).cuadrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.cuadradoResponse> AplicacionCalculadora.ServicioCalculadora.Calculadora.cuadradoAsync(AplicacionCalculadora.ServicioCalculadora.cuadradoRequest request) {
            return base.Channel.cuadradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionCalculadora.ServicioCalculadora.cuadradoResponse> cuadradoAsync(double arg0) {
            AplicacionCalculadora.ServicioCalculadora.cuadradoRequest inValue = new AplicacionCalculadora.ServicioCalculadora.cuadradoRequest();
            inValue.arg0 = arg0;
            return ((AplicacionCalculadora.ServicioCalculadora.Calculadora)(this)).cuadradoAsync(inValue);
        }
    }
}
